const LegalDisclaimer = () => {
  return (
    <section
      className="legal-disclaimer"
      aria-labelledby="financial-disclaimer-title"
    >
      <h2 id="financial-disclaimer-title">
        Important financial information
      </h2>

      <p>
        SmartExpense is a personal expense and financial organization tool.
        Information, calculations, analytics, projections, recommendations,
        and insights generated by the application are provided for
        informational and organizational purposes.
      </p>

      <p>
        SmartExpense does not provide investment, tax, legal, accounting,
        lending, insurance, or other regulated professional advice.
      </p>

      <p>
        Users should independently verify important financial decisions with
        an appropriately qualified professional.
      </p>
    </section>
  );
};

export default LegalDisclaimer;